export { About } from './About'
export { Contact } from './Contact'
export { Landing } from './Landing'
export { Services } from './Services'
export { MemberPage } from './MemberPage'
export { ProjectDetailPage } from './ProjectDetailPage'